- name: install apache2
  hosts: all
  vars:
    a: apache2
    b: present
    c: yes

  tasks:
    - name: instal apache2
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
    - name: chage content
      copy:
        content: ok
        dest: /var/www/html/index.html
    - name: restart server
      service:
        name: apache2
        state: restarted
    - name: connectivity
      uri:
        url: http://172.31.26.17
        status_code: 200
